# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.srcs/sources_1/bd/fft_ip/fft_ip.bd
# Block Designs: The module: 'fft_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.srcs/sources_1/bd/fft_ip/ip/fft_ip_xfft_0_0/fft_ip_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xfft_0_0 || ORIG_REF_NAME==fft_ip_xfft_0_0} -quiet] -quiet

# XDC: c:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.gen/sources_1/bd/fft_ip/fft_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_ip'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.srcs/sources_1/bd/fft_ip/fft_ip.bd
# Block Designs: The module: 'fft_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.srcs/sources_1/bd/fft_ip/ip/fft_ip_xfft_0_0/fft_ip_xfft_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xfft_0_0 || ORIG_REF_NAME==fft_ip_xfft_0_0} -quiet] -quiet

# XDC: c:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.gen/sources_1/bd/fft_ip/fft_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_ip'. Do not add the DONT_TOUCH constraint.
