# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.srcs/sources_1/ip/sym2_bram/sym2_bram.xci
# IP: The module: 'sym2_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.gen/sources_1/ip/sym2_bram/sym2_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sym2_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.srcs/sources_1/ip/sym2_bram/sym2_bram.xci
# IP: The module: 'sym2_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.gen/sources_1/ip/sym2_bram/sym2_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sym2_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
