# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft_ip/fft_ip.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip || ORIG_REF_NAME==fft_ip} -quiet] -quiet

# IP: bd/fft_ip/ip/fft_ip_xfft_0_0/fft_ip_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xfft_0_0 || ORIG_REF_NAME==fft_ip_xfft_0_0} -quiet] -quiet

# IP: bd/fft_ip/ip/fft_ip_xlconcat_0_0/fft_ip_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xlconcat_0_0 || ORIG_REF_NAME==fft_ip_xlconcat_0_0} -quiet] -quiet

# IP: bd/fft_ip/ip/fft_ip_xlslice_0_0/fft_ip_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xlslice_0_0 || ORIG_REF_NAME==fft_ip_xlslice_0_0} -quiet] -quiet

# IP: bd/fft_ip/ip/fft_ip_xlslice_1_0/fft_ip_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xlslice_1_0 || ORIG_REF_NAME==fft_ip_xlslice_1_0} -quiet] -quiet

# IP: bd/fft_ip/ip/fft_ip_xlconstant_0_0/fft_ip_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xlconstant_0_0 || ORIG_REF_NAME==fft_ip_xlconstant_0_0} -quiet] -quiet

# IP: bd/fft_ip/ip/fft_ip_xlconstant_1_0/fft_ip_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_ip_xlconstant_1_0 || ORIG_REF_NAME==fft_ip_xlconstant_1_0} -quiet] -quiet

# XDC: c:/Users/priya/MTTS-Signal-Processing-TS-LINK/ofdm_transmitter_hdl/ofdm_transmitter.gen/sources_1/bd/fft_ip/fft_ip_ooc.xdc
